<?php

function prefix_icons($icons)
{
    return array_map(function ($icon) {
        return 'heroicon-o-' . $icon;
    }, $icons);
}


return [
    /*
    |--------------------------------------------------------------------------
    | FilamentPHP Heroicons Configuration
    |--------------------------------------------------------------------------
    |
    | This file contains the configuration for Heroicons used in FilamentPHP.
    | Each icon is defined with its key (heroicon-o-{name}) and translation key.
    |
    */

    'icons' => [
        'heroicon-o-academic-cap' => 'filament_heroicons.academic_cap',
        'heroicon-o-adjustments-horizontal' => 'filament_heroicons.adjustments_horizontal',
        'heroicon-o-adjustments-vertical' => 'filament_heroicons.adjustments_vertical',
        'heroicon-o-archive-box-arrow-down' => 'filament_heroicons.archive_box_arrow_down',
        'heroicon-o-archive-box-x-mark' => 'filament_heroicons.archive_box_x_mark',
        'heroicon-o-archive-box' => 'filament_heroicons.archive_box',
        'heroicon-o-arrow-down-circle' => 'filament_heroicons.arrow_down_circle',
        'heroicon-o-arrow-down-left' => 'filament_heroicons.arrow_down_left',
        'heroicon-o-arrow-down-on-square-stack' => 'filament_heroicons.arrow_down_on_square_stack',
        'heroicon-o-arrow-down-on-square' => 'filament_heroicons.arrow_down_on_square',
        'heroicon-o-arrow-down-right' => 'filament_heroicons.arrow_down_right',
        'heroicon-o-arrow-down-tray' => 'filament_heroicons.arrow_down_tray',
        'heroicon-o-arrow-down' => 'filament_heroicons.arrow_down',
        'heroicon-o-arrow-left-circle' => 'filament_heroicons.arrow_left_circle',
        'heroicon-o-arrow-left-end-on-rectangle' => 'filament_heroicons.arrow_left_end_on_rectangle',
        'heroicon-o-arrow-left-start-on-rectangle' => 'filament_heroicons.arrow_left_start_on_rectangle',
        'heroicon-o-arrow-left' => 'filament_heroicons.arrow_left',
        'heroicon-o-arrow-long-down' => 'filament_heroicons.arrow_long_down',
        'heroicon-o-arrow-long-left' => 'filament_heroicons.arrow_long_left',
        'heroicon-o-arrow-long-right' => 'filament_heroicons.arrow_long_right',
        'heroicon-o-arrow-long-up' => 'filament_heroicons.arrow_long_up',
        'heroicon-o-arrow-path-rounded-square' => 'filament_heroicons.arrow_path_rounded_square',
        'heroicon-o-arrow-path' => 'filament_heroicons.arrow_path',
        'heroicon-o-arrow-right-circle' => 'filament_heroicons.arrow_right_circle',
        'heroicon-o-arrow-right-end-on-rectangle' => 'filament_heroicons.arrow_right_end_on_rectangle',
        'heroicon-o-arrow-right-start-on-rectangle' => 'filament_heroicons.arrow_right_start_on_rectangle',
        'heroicon-o-arrow-right' => 'filament_heroicons.arrow_right',
        'heroicon-o-arrow-top-right-on-square' => 'filament_heroicons.arrow_top_right_on_square',
        'heroicon-o-arrow-trending-down' => 'filament_heroicons.arrow_trending_down',
        'heroicon-o-arrow-trending-up' => 'filament_heroicons.arrow_trending_up',
        'heroicon-o-arrow-turn-down-left' => 'filament_heroicons.arrow_turn_down_left',
        'heroicon-o-arrow-turn-down-right' => 'filament_heroicons.arrow_turn_down_right',
        'heroicon-o-arrow-turn-left-down' => 'filament_heroicons.arrow_turn_left_down',
        'heroicon-o-arrow-turn-left-up' => 'filament_heroicons.arrow_turn_left_up',
        'heroicon-o-arrow-turn-right-down' => 'filament_heroicons.arrow_turn_right_down',
        'heroicon-o-arrow-turn-right-up' => 'filament_heroicons.arrow_turn_right_up',
        'heroicon-o-arrow-turn-up-left' => 'filament_heroicons.arrow_turn_up_left',
        'heroicon-o-arrow-turn-up-right' => 'filament_heroicons.arrow_turn_up_right',
        'heroicon-o-arrow-up-circle' => 'filament_heroicons.arrow_up_circle',
        'heroicon-o-arrow-up-left' => 'filament_heroicons.arrow_up_left',
        'heroicon-o-arrow-up-on-square-stack' => 'filament_heroicons.arrow_up_on_square_stack',
        'heroicon-o-arrow-up-on-square' => 'filament_heroicons.arrow_up_on_square',
        'heroicon-o-arrow-up-right' => 'filament_heroicons.arrow_up_right',
        'heroicon-o-arrow-up-tray' => 'filament_heroicons.arrow_up_tray',
        'heroicon-o-arrow-up' => 'filament_heroicons.arrow_up',
        'heroicon-o-arrow-uturn-down' => 'filament_heroicons.arrow_uturn_down',
        'heroicon-o-arrow-uturn-left' => 'filament_heroicons.arrow_uturn_left',
        'heroicon-o-arrow-uturn-right' => 'filament_heroicons.arrow_uturn_right',
        'heroicon-o-arrow-uturn-up' => 'filament_heroicons.arrow_uturn_up',
        'heroicon-o-arrows-pointing-in' => 'filament_heroicons.arrows_pointing_in',
        'heroicon-o-arrows-pointing-out' => 'filament_heroicons.arrows_pointing_out',
        'heroicon-o-arrows-right-left' => 'filament_heroicons.arrows_right_left',
        'heroicon-o-arrows-up-down' => 'filament_heroicons.arrows_up_down',
        'heroicon-o-at-symbol' => 'filament_heroicons.at_symbol',
        'heroicon-o-backspace' => 'filament_heroicons.backspace',
        'heroicon-o-backward' => 'filament_heroicons.backward',
        'heroicon-o-banknotes' => 'filament_heroicons.banknotes',
        'heroicon-o-bars-2' => 'filament_heroicons.bars_2',
        'heroicon-o-bars-3-bottom-left' => 'filament_heroicons.bars_3_bottom_left',
        'heroicon-o-bars-3-bottom-right' => 'filament_heroicons.bars_3_bottom_right',
        'heroicon-o-bars-3-center-left' => 'filament_heroicons.bars_3_center_left',
        'heroicon-o-bars-3' => 'filament_heroicons.bars_3',
        'heroicon-o-bars-4' => 'filament_heroicons.bars_4',
        'heroicon-o-bars-arrow-down' => 'filament_heroicons.bars_arrow_down',
        'heroicon-o-bars-arrow-up' => 'filament_heroicons.bars_arrow_up',
        'heroicon-o-battery-0' => 'filament_heroicons.battery_0',
        'heroicon-o-battery-100' => 'filament_heroicons.battery_100',
        'heroicon-o-battery-50' => 'filament_heroicons.battery_50',
        'heroicon-o-beaker' => 'filament_heroicons.beaker',
        'heroicon-o-bell-alert' => 'filament_heroicons.bell_alert',
        'heroicon-o-bell-slash' => 'filament_heroicons.bell_slash',
        'heroicon-o-bell-snooze' => 'filament_heroicons.bell_snooze',
        'heroicon-o-bell' => 'filament_heroicons.bell',
        'heroicon-o-bold' => 'filament_heroicons.bold',
        'heroicon-o-bolt-slash' => 'filament_heroicons.bolt_slash',
        'heroicon-o-bolt' => 'filament_heroicons.bolt',
        'heroicon-o-book-open' => 'filament_heroicons.book_open',
        'heroicon-o-bookmark-slash' => 'filament_heroicons.bookmark_slash',
        'heroicon-o-bookmark-square' => 'filament_heroicons.bookmark_square',
        'heroicon-o-bookmark' => 'filament_heroicons.bookmark',
        'heroicon-o-briefcase' => 'filament_heroicons.briefcase',
        'heroicon-o-bug-ant' => 'filament_heroicons.bug_ant',
        'heroicon-o-building-library' => 'filament_heroicons.building_library',
        'heroicon-o-building-office-2' => 'filament_heroicons.building_office_2',
        'heroicon-o-building-office' => 'filament_heroicons.building_office',
        'heroicon-o-building-storefront' => 'filament_heroicons.building_storefront',
        'heroicon-o-cake' => 'filament_heroicons.cake',
        'heroicon-o-calculator' => 'filament_heroicons.calculator',
        'heroicon-o-calendar-date-range' => 'filament_heroicons.calendar_date_range',
        'heroicon-o-calendar-days' => 'filament_heroicons.calendar_days',
        'heroicon-o-calendar' => 'filament_heroicons.calendar',
        'heroicon-o-camera' => 'filament_heroicons.camera',
        'heroicon-o-chart-bar-square' => 'filament_heroicons.chart_bar_square',
        'heroicon-o-chart-bar' => 'filament_heroicons.chart_bar',
        'heroicon-o-chart-pie' => 'filament_heroicons.chart_pie',
        'heroicon-o-chat-bubble-bottom-center-text' => 'filament_heroicons.chat_bubble_bottom_center_text',
        'heroicon-o-chat-bubble-bottom-center' => 'filament_heroicons.chat_bubble_bottom_center',
        'heroicon-o-chat-bubble-left-ellipsis' => 'filament_heroicons.chat_bubble_left_ellipsis',
        'heroicon-o-chat-bubble-left-right' => 'filament_heroicons.chat_bubble_left_right',
        'heroicon-o-chat-bubble-left' => 'filament_heroicons.chat_bubble_left',
        'heroicon-o-chat-bubble-oval-left-ellipsis' => 'filament_heroicons.chat_bubble_oval_left_ellipsis',
        'heroicon-o-chat-bubble-oval-left' => 'filament_heroicons.chat_bubble_oval_left',
        'heroicon-o-check-badge' => 'filament_heroicons.check_badge',
        'heroicon-o-check-circle' => 'filament_heroicons.check_circle',
        'heroicon-o-check' => 'filament_heroicons.check',
        'heroicon-o-chevron-double-down' => 'filament_heroicons.chevron_double_down',
        'heroicon-o-chevron-double-left' => 'filament_heroicons.chevron_double_left',
        'heroicon-o-chevron-double-right' => 'filament_heroicons.chevron_double_right',
        'heroicon-o-chevron-double-up' => 'filament_heroicons.chevron_double_up',
        'heroicon-o-chevron-down' => 'filament_heroicons.chevron_down',
        'heroicon-o-chevron-left' => 'filament_heroicons.chevron_left',
        'heroicon-o-chevron-right' => 'filament_heroicons.chevron_right',
        'heroicon-o-chevron-up-down' => 'filament_heroicons.chevron_up_down',
        'heroicon-o-chevron-up' => 'filament_heroicons.chevron_up',
        'heroicon-o-circle-stack' => 'filament_heroicons.circle_stack',
        'heroicon-o-clipboard-document-check' => 'filament_heroicons.clipboard_document_check',
        'heroicon-o-clipboard-document-list' => 'filament_heroicons.clipboard_document_list',
        'heroicon-o-clipboard-document' => 'filament_heroicons.clipboard_document',
        'heroicon-o-clipboard' => 'filament_heroicons.clipboard',
        'heroicon-o-clock' => 'filament_heroicons.clock',
        'heroicon-o-cloud-arrow-down' => 'filament_heroicons.cloud_arrow_down',
        'heroicon-o-cloud-arrow-up' => 'filament_heroicons.cloud_arrow_up',
        'heroicon-o-cloud' => 'filament_heroicons.cloud',
        'heroicon-o-code-bracket-square' => 'filament_heroicons.code_bracket_square',
        'heroicon-o-code-bracket' => 'filament_heroicons.code_bracket',
        'heroicon-o-cog-6-tooth' => 'filament_heroicons.cog_6_tooth',
        'heroicon-o-cog-8-tooth' => 'filament_heroicons.cog_8_tooth',
        'heroicon-o-cog' => 'filament_heroicons.cog',
        'heroicon-o-command-line' => 'filament_heroicons.command_line',
        'heroicon-o-computer-desktop' => 'filament_heroicons.computer_desktop',
        'heroicon-o-cpu-chip' => 'filament_heroicons.cpu_chip',
        'heroicon-o-credit-card' => 'filament_heroicons.credit_card',
        'heroicon-o-cube-transparent' => 'filament_heroicons.cube_transparent',
        'heroicon-o-cube' => 'filament_heroicons.cube',
        'heroicon-o-currency-bangladeshi' => 'filament_heroicons.currency_bangladeshi',
        'heroicon-o-currency-dollar' => 'filament_heroicons.currency_dollar',
        'heroicon-o-currency-euro' => 'filament_heroicons.currency_euro',
        'heroicon-o-currency-pound' => 'filament_heroicons.currency_pound',
        'heroicon-o-currency-rupee' => 'filament_heroicons.currency_rupee',
        'heroicon-o-currency-yen' => 'filament_heroicons.currency_yen',
        'heroicon-o-cursor-arrow-rays' => 'filament_heroicons.cursor_arrow_rays',
        'heroicon-o-cursor-arrow-ripple' => 'filament_heroicons.cursor_arrow_ripple',
        'heroicon-o-device-phone-mobile' => 'filament_heroicons.device_phone_mobile',
        'heroicon-o-device-tablet' => 'filament_heroicons.device_tablet',
        'heroicon-o-divide' => 'filament_heroicons.divide',
        'heroicon-o-document-arrow-down' => 'filament_heroicons.document_arrow_down',
        'heroicon-o-document-arrow-up' => 'filament_heroicons.document_arrow_up',
        'heroicon-o-document-chart-bar' => 'filament_heroicons.document_chart_bar',
        'heroicon-o-document-check' => 'filament_heroicons.document_check',
        'heroicon-o-document-currency-bangladeshi' => 'filament_heroicons.document_currency_bangladeshi',
        'heroicon-o-document-currency-dollar' => 'filament_heroicons.document_currency_dollar',
        'heroicon-o-document-currency-euro' => 'filament_heroicons.document_currency_euro',
        'heroicon-o-document-currency-pound' => 'filament_heroicons.document_currency_pound',
        'heroicon-o-document-currency-rupee' => 'filament_heroicons.document_currency_rupee',
        'heroicon-o-document-currency-yen' => 'filament_heroicons.document_currency_yen',
        'heroicon-o-document-duplicate' => 'filament_heroicons.document_duplicate',
        'heroicon-o-document-magnifying-glass' => 'filament_heroicons.document_magnifying_glass',
        'heroicon-o-document-minus' => 'filament_heroicons.document_minus',
        'heroicon-o-document-plus' => 'filament_heroicons.document_plus',
        'heroicon-o-document-text' => 'filament_heroicons.document_text',
        'heroicon-o-document' => 'filament_heroicons.document',
        'heroicon-o-ellipsis-horizontal-circle' => 'filament_heroicons.ellipsis_horizontal_circle',
        'heroicon-o-ellipsis-horizontal' => 'filament_heroicons.ellipsis_horizontal',
        'heroicon-o-ellipsis-vertical' => 'filament_heroicons.ellipsis_vertical',
        'heroicon-o-envelope-open' => 'filament_heroicons.envelope_open',
        'heroicon-o-envelope' => 'filament_heroicons.envelope',
        'heroicon-o-equals' => 'filament_heroicons.equals',
        'heroicon-o-exclamation-circle' => 'filament_heroicons.exclamation_circle',
        'heroicon-o-exclamation-triangle' => 'filament_heroicons.exclamation_triangle',
        'heroicon-o-eye-dropper' => 'filament_heroicons.eye_dropper',
        'heroicon-o-eye-slash' => 'filament_heroicons.eye_slash',
        'heroicon-o-eye' => 'filament_heroicons.eye',
        'heroicon-o-face-frown' => 'filament_heroicons.face_frown',
        'heroicon-o-face-smile' => 'filament_heroicons.face_smile',
        'heroicon-o-film' => 'filament_heroicons.film',
        'heroicon-o-finger-print' => 'filament_heroicons.finger_print',
        'heroicon-o-fire' => 'filament_heroicons.fire',
        'heroicon-o-flag' => 'filament_heroicons.flag',
        'heroicon-o-folder-arrow-down' => 'filament_heroicons.folder_arrow_down',
        'heroicon-o-folder-minus' => 'filament_heroicons.folder_minus',
        'heroicon-o-folder-open' => 'filament_heroicons.folder_open',
        'heroicon-o-folder-plus' => 'filament_heroicons.folder_plus',
        'heroicon-o-folder' => 'filament_heroicons.folder',
        'heroicon-o-forward' => 'filament_heroicons.forward',
        'heroicon-o-funnel' => 'filament_heroicons.funnel',
        'heroicon-o-gif' => 'filament_heroicons.gif',
        'heroicon-o-gift-top' => 'filament_heroicons.gift_top',
        'heroicon-o-gift' => 'filament_heroicons.gift',
        'heroicon-o-globe-alt' => 'filament_heroicons.globe_alt',
        'heroicon-o-globe-americas' => 'filament_heroicons.globe_americas',
        'heroicon-o-globe-asia-australia' => 'filament_heroicons.globe_asia_australia',
        'heroicon-o-globe-europe-africa' => 'filament_heroicons.globe_europe_africa',
        'heroicon-o-h1' => 'filament_heroicons.h1',
        'heroicon-o-h2' => 'filament_heroicons.h2',
        'heroicon-o-h3' => 'filament_heroicons.h3',
        'heroicon-o-hand-raised' => 'filament_heroicons.hand_raised',
        'heroicon-o-hand-thumb-down' => 'filament_heroicons.hand_thumb_down',
        'heroicon-o-hand-thumb-up' => 'filament_heroicons.hand_thumb_up',
        'heroicon-o-hashtag' => 'filament_heroicons.hashtag',
        'heroicon-o-heart' => 'filament_heroicons.heart',
        'heroicon-o-home-modern' => 'filament_heroicons.home_modern',
        'heroicon-o-home' => 'filament_heroicons.home',
        'heroicon-o-identification' => 'filament_heroicons.identification',
        'heroicon-o-inbox-arrow-down' => 'filament_heroicons.inbox_arrow_down',
        'heroicon-o-inbox-stack' => 'filament_heroicons.inbox_stack',
        'heroicon-o-inbox' => 'filament_heroicons.inbox',
        'heroicon-o-information-circle' => 'filament_heroicons.information_circle',
        'heroicon-o-italic' => 'filament_heroicons.italic',
        'heroicon-o-key' => 'filament_heroicons.key',
        'heroicon-o-language' => 'filament_heroicons.language',
        'heroicon-o-lifebuoy' => 'filament_heroicons.lifebuoy',
        'heroicon-o-light-bulb' => 'filament_heroicons.light_bulb',
        'heroicon-o-link-slash' => 'filament_heroicons.link_slash',
        'heroicon-o-link' => 'filament_heroicons.link',
        'heroicon-o-list-bullet' => 'filament_heroicons.list_bullet',
        'heroicon-o-lock-closed' => 'filament_heroicons.lock_closed',
        'heroicon-o-lock-open' => 'filament_heroicons.lock_open',
        'heroicon-o-magnifying-glass-circle' => 'filament_heroicons.magnifying_glass_circle',
        'heroicon-o-magnifying-glass-minus' => 'filament_heroicons.magnifying_glass_minus',
        'heroicon-o-magnifying-glass-plus' => 'filament_heroicons.magnifying_glass_plus',
        'heroicon-o-magnifying-glass' => 'filament_heroicons.magnifying_glass',
        'heroicon-o-map-pin' => 'filament_heroicons.map_pin',
        'heroicon-o-map' => 'filament_heroicons.map',
        'heroicon-o-megaphone' => 'filament_heroicons.megaphone',
        'heroicon-o-microphone' => 'filament_heroicons.microphone',
        'heroicon-o-minus-circle' => 'filament_heroicons.minus_circle',
        'heroicon-o-minus' => 'filament_heroicons.minus',
        'heroicon-o-moon' => 'filament_heroicons.moon',
        'heroicon-o-musical-note' => 'filament_heroicons.musical_note',
        'heroicon-o-newspaper' => 'filament_heroicons.newspaper',
        'heroicon-o-no-symbol' => 'filament_heroicons.no_symbol',
        'heroicon-o-numbered-list' => 'filament_heroicons.numbered_list',
        'heroicon-o-paint-brush' => 'filament_heroicons.paint_brush',
        'heroicon-o-paper-airplane' => 'filament_heroicons.paper_airplane',
        'heroicon-o-paper-clip' => 'filament_heroicons.paper_clip',
        'heroicon-o-pause-circle' => 'filament_heroicons.pause_circle',
        'heroicon-o-pause' => 'filament_heroicons.pause',
        'heroicon-o-pencil-square' => 'filament_heroicons.pencil_square',
        'heroicon-o-pencil' => 'filament_heroicons.pencil',
        'heroicon-o-percent-badge' => 'filament_heroicons.percent_badge',
        'heroicon-o-phone-arrow-down-left' => 'filament_heroicons.phone_arrow_down_left',
        'heroicon-o-phone-arrow-up-right' => 'filament_heroicons.phone_arrow_up_right',
        'heroicon-o-phone-x-mark' => 'filament_heroicons.phone_x_mark',
        'heroicon-o-phone' => 'filament_heroicons.phone',
        'heroicon-o-photo' => 'filament_heroicons.photo',
        'heroicon-o-play-circle' => 'filament_heroicons.play_circle',
        'heroicon-o-play-pause' => 'filament_heroicons.play_pause',
        'heroicon-o-play' => 'filament_heroicons.play',
        'heroicon-o-plus-circle' => 'filament_heroicons.plus_circle',
        'heroicon-o-plus' => 'filament_heroicons.plus',
        'heroicon-o-power' => 'filament_heroicons.power',
        'heroicon-o-presentation-chart-bar' => 'filament_heroicons.presentation_chart_bar',
        'heroicon-o-presentation-chart-line' => 'filament_heroicons.presentation_chart_line',
        'heroicon-o-printer' => 'filament_heroicons.printer',
        'heroicon-o-puzzle-piece' => 'filament_heroicons.puzzle_piece',
        'heroicon-o-qr-code' => 'filament_heroicons.qr_code',
        'heroicon-o-question-mark-circle' => 'filament_heroicons.question_mark_circle',
        'heroicon-o-queue-list' => 'filament_heroicons.queue_list',
        'heroicon-o-radio' => 'filament_heroicons.radio',
        'heroicon-o-receipt-percent' => 'filament_heroicons.receipt_percent',
        'heroicon-o-receipt-refund' => 'filament_heroicons.receipt_refund',
        'heroicon-o-rectangle-group' => 'filament_heroicons.rectangle_group',
        'heroicon-o-rectangle-stack' => 'filament_heroicons.rectangle_stack',
        'heroicon-o-rocket-launch' => 'filament_heroicons.rocket_launch',
        'heroicon-o-rss' => 'filament_heroicons.rss',
        'heroicon-o-scale' => 'filament_heroicons.scale',
        'heroicon-o-scissors' => 'filament_heroicons.scissors',
        'heroicon-o-server-stack' => 'filament_heroicons.server_stack',
        'heroicon-o-server' => 'filament_heroicons.server',
        'heroicon-o-share' => 'filament_heroicons.share',
        'heroicon-o-shield-check' => 'filament_heroicons.shield_check',
        'heroicon-o-shield-exclamation' => 'filament_heroicons.shield_exclamation',
        'heroicon-o-shopping-bag' => 'filament_heroicons.shopping_bag',
        'heroicon-o-shopping-cart' => 'filament_heroicons.shopping_cart',
        'heroicon-o-signal-slash' => 'filament_heroicons.signal_slash',
        'heroicon-o-signal' => 'filament_heroicons.signal',
        'heroicon-o-slash' => 'filament_heroicons.slash',
        'heroicon-o-sparkles' => 'filament_heroicons.sparkles',
        'heroicon-o-speaker-wave' => 'filament_heroicons.speaker_wave',
        'heroicon-o-speaker-x-mark' => 'filament_heroicons.speaker_x_mark',
        'heroicon-o-square-2-stack' => 'filament_heroicons.square_2_stack',
        'heroicon-o-square-3-stack-3d' => 'filament_heroicons.square_3_stack_3d',
        'heroicon-o-squares-2x2' => 'filament_heroicons.squares_2x2',
        'heroicon-o-squares-plus' => 'filament_heroicons.squares_plus',
        'heroicon-o-star' => 'filament_heroicons.star',
        'heroicon-o-stop-circle' => 'filament_heroicons.stop_circle',
        'heroicon-o-stop' => 'filament_heroicons.stop',
        'heroicon-o-strikethrough' => 'filament_heroicons.strikethrough',
        'heroicon-o-sun' => 'filament_heroicons.sun',
        'heroicon-o-swatch' => 'filament_heroicons.swatch',
        'heroicon-o-table-cells' => 'filament_heroicons.table_cells',
        'heroicon-o-tag' => 'filament_heroicons.tag',
        'heroicon-o-ticket' => 'filament_heroicons.ticket',
        'heroicon-o-trash' => 'filament_heroicons.trash',
        'heroicon-o-trophy' => 'filament_heroicons.trophy',
        'heroicon-o-truck' => 'filament_heroicons.truck',
        'heroicon-o-tv' => 'filament_heroicons.tv',
        'heroicon-o-underline' => 'filament_heroicons.underline',
        'heroicon-o-user-circle' => 'filament_heroicons.user_circle',
        'heroicon-o-user-group' => 'filament_heroicons.user_group',
        'heroicon-o-user-minus' => 'filament_heroicons.user_minus',
        'heroicon-o-user-plus' => 'filament_heroicons.user_plus',
        'heroicon-o-user' => 'filament_heroicons.user',
        'heroicon-o-users' => 'filament_heroicons.users',
        'heroicon-o-variable' => 'filament_heroicons.variable',
        'heroicon-o-video-camera-slash' => 'filament_heroicons.video_camera_slash',
        'heroicon-o-video-camera' => 'filament_heroicons.video_camera',
        'heroicon-o-view-columns' => 'filament_heroicons.view_columns',
        'heroicon-o-viewfinder-circle' => 'filament_heroicons.viewfinder_circle',
        'heroicon-o-wallet' => 'filament_heroicons.wallet',
        'heroicon-o-wifi' => 'filament_heroicons.wifi',
        'heroicon-o-window' => 'filament_heroicons.window',
        'heroicon-o-wrench-screwdriver' => 'filament_heroicons.wrench_screwdriver',
        'heroicon-o-wrench' => 'filament_heroicons.wrench',
        'heroicon-o-x-circle' => 'filament_heroicons.x_circle',
        'heroicon-o-x-mark' => 'filament_heroicons.x_mark',
    ],

    /*
    |--------------------------------------------------------------------------
    | Icon Categories
    |--------------------------------------------------------------------------
    |
    | Group icons by category for better organization when needed
    |
    */
    'categories' => [
        'actions' => prefix_icons([
            'pencil',
            'trash',
            'cog',
            'plus',
            'minus',
            'edit',
            'save',
            'share',
            'download',
            'upload'
        ]),

        'media' => prefix_icons([
            'photo',
            'video-camera',
            'film',
            'musical-note',
            'play',
            'pause',
            'stop'
        ]),

        'communication' => prefix_icons([
            'chat-bubble-left',
            'chat-bubble-left-right',
            'envelope',
            'phone',
            'bell',
            'megaphone'
        ]),

        'security' => prefix_icons([
            'lock-closed',
            'lock-open',
            'shield-check',
            'shield-exclamation',
            'key',
            'finger-print'
        ]),

        'user' => prefix_icons([
            'user',
            'user-group',
            'user-circle',
            'user-plus',
            'user-minus',
            'users'
        ]),

        'files' => prefix_icons([
            'document',
            'folder',
            'clipboard',
            'paper-clip',
            'archive-box',
            'inbox'
        ]),

        'commerce' => prefix_icons([
            'shopping-cart',
            'shopping-bag',
            'credit-card',
            'banknotes',
            'currency-dollar',
            'receipt-percent'
        ]),

        'status' => prefix_icons([
            'check',
            'x-mark',
            'exclamation-triangle',
            'information-circle',
            'check-circle',
            'x-circle'
        ])
    ],
];
